### PR TITLE
View error handling

### PR DESCRIPTION
**Pull request by RoverWire**
This changes, handles errors in case of non existent/reachable view file.

### CODE REVIEW

**Comment by gregmolnar** [comment]
Thanks for this fix. Would you mind redo this against the updated master branch? I made some changes to the framework a while ago and just updated master with those.

**Comment by RoverWire** [comment]
Sure, no problem!

**Comment by gregmolnar** [comment]
Thank you!

**Comment by RoverWire** [comment]
Done!

**Comment by RoverWire** [comment]
My Bad, I didn't notice the other changes in the framework file.

**Comment by RoverWire** [comment]
@gregmolnar Now is ready!

**Pull request closed without merging**
